// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upgrades.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeUserById = `-- name: UpgradeUserById :execrows
UPDATE users
SET is_chirpy_red = '1'
WHERE id = $1
`

func (q *Queries) UpgradeUserById(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, upgradeUserById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
